"""add_course_and_roadmap_tables

Revision ID: b82a1f5335a3
Revises: 5a9a71c03ae0
Create Date: 2026-04-26 02:13:25.916462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82a1f5335a3'
down_revision: Union[str, Sequence[str], None] = '5a9a71c03ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
